import './globals.css'
import localFont from 'next/font/local'

const myfont = localFont({
  src: [
    {
      path: '../public/assets/fonts/bYekanRegular.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-byekan',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={myfont.className}>
      <body className={`${myfont.variable}`}>{children}</body>
    </html>
  )
}
